### PR TITLE
WIP: programatic flot incorporation. run #1 works!

### PR DESCRIPTION
**Pull request by sasen**
-- not happy with where script is stored right now
-- may move javascript-generating function to processLib

### CODE REVIEW

**Comment by satra** [comment]
@akeshavan can you review this? i'll start reviewing things once i have a better grasp of this code.

**Comment by sasen** [comment]
@satra @akeshavan i just want to make it clear that, even though anisha merged an earlier version of this PR#1 into her PR#2, this PR still needs review and needs to be merged into gablab/realtime's master.

**Comment by akeshavan** [comment]
@sasen good point, reviewing now

**Comment by akeshavan** [comment]
Was able to run rt run#1, but I found 2 errors so far:
1) flot doesn't work for me
2) When I click 'End Murfi', 'End RT' and 'End Serve' get disabled 
@sasen if we could meed sometime today and talk through the logic part of the code that would be really helpful for me.

**Comment by akeshavan** [comment]
@sasen I'm really not sure why flot isn't working, does it work for you on Texas? Since I'm not too familiar with javascript it would be good to talk this out together sometime today

**Comment by sasen** [comment]
@akeshavan, flot isn't working for me right now on texas. When I pushed the PR on Friday, it did, but since then, I've continued work on it, and it doesn't work as of my last commit. It's still what it says on the tin, a WIP.

**Comment by sasen** [comment]
End Murfi: Ah, thanks for pointing out that I should ensure those process handles are closed before disabling the buttons. Maybe it would just be cleaner to have the psychopy and servenii buttons be single-action (launch and then immediately disable), and End murfi should have to deal with the cleanup? @akeshavan, thoughts?

About the PR: why is button-logic being fully functional (not a low-hanging fruit), a blocking condition on approving a WIP commit on a different task (flot incorporation, supposedly low-hanging)? If the answer is that WIPs should not be PRed, then please CLOSE my request.

**Comment by sasen** [comment]
@akeshavan also, my apologies on failing to talk through the logic today as you requested. We will definitely meet tomorrow, and I will also try to write out some notes by then. Certainly explaining it to someone else is a fantastic way to reveal design problems, so I am quite excited to meet.

**Comment by akeshavan** [comment]
Yeah I think making murfi and launch RT one button would help a lot, and lets not close your request because having it up here is helpful so we can talk it through on here. Also i don't think flot is low hanging because I was struggling with that today!

**Pull request merged**
