### PR TITLE
psychoFileSelection

### PR DESCRIPTION
**Pull request by sasen**
Patches Pull Request #8.

### CODE REVIEW

**Comment by sasen** [comment]
I'm going to work on merging this first. will push a new merged commit soon. fresh testing files will take some more time though.
EDIT: Done. Ready for review now!

**Comment by sasen** [comment]
I'm noticing some more incompatibilities between mTBI_rt.py and mTBI_rt_placebo.py. For instance, placebo uses the old filename style. Its logic for drawing feedback may also be out of date? I'm not sure. However, I recommend accepting the pull request to allow us both to work on fixing it.

**Comment by akeshavan** [comment]
Yep placebo is out of date - but its not showing any feedback. I'll look at combining the two, unless you've already started that

**Comment by sasen** [comment]
@akeshavan placebo (& train & placebo_train): all yours. 

much thanks,
--ss

**Pull request merged**
