### PR TITLE
enh: added modal to set group (high or low)

### PR DESCRIPTION
**Pull request by akeshavan**
added a modal to set group! @sasen test it out!

### CODE REVIEW

**Comment by akeshavan** [comment]
don't merge yet, need to remove cancel button and only enable ok button when a value is clicked!

**Comment by sasen** [comment]
ok @akeshavan,  let me know when.
also can you make the correct realtime stimulus  (mTBI_rt_placebo.py for low dose) get used in the JSON please?
or do you need that to be a separate feature/branch/PR?

**Comment by sasen** [comment]
for what it's worth, this is a great example of the login issues i've been talking about: 
- create a new subject, assign to whatever group.
- logout
- create another new subject
  ==> you don't get a modal, and it keeps the same variable values as the 1st new subject.

so i think we have instance variables confused with class variables. of course, i don't mind if that bug gets fixed in a different feature branch; i'll still approve this one for adding the modal.

**Comment by sasen** [comment]
@akeshavan, wait: why remove the "cancel" button? we want that in there so that the user can catch their typos, like 'pilto17' instead of 'pilot17'.

EDIT: it would be better if the cancel button doesn't allow the typoed subjectID directory creation. Also, it should bring you back to the login page, not an empty, broken logged-in state.

**Comment by akeshavan** [comment]
@sasen yep cancel button now brings you back to login
I think its ready for merge, after I'm going to start a new PR with cherrypy sessions because now the problem is clear

**Comment by akeshavan** [comment]
And I forgot to make a new branch for the above commit. Sorry! Please test! I put a deepcopy of j.info and that seemed to make a difference.

**Pull request merged**
